image: docker:git
services:
- docker:dind

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - git clone https://github.com/giuseppe/ostreetests.git --depth 1 -b master
  - git clone https://github.com/gbraad/ostreetests.git mine --depth 1 -b master


build_centos:
  script:
    - docker build -t registry.gitlab.com/gbraad/ostreetests:centos ./ostreetests/centos
    - docker push registry.gitlab.com/gbraad/ostreetests:centos
  only:
    - master
  when: manual

build_fedora:
  script:
    - docker build -t registry.gitlab.com/gbraad/ostreetests:fedora ./ostreetests/fedora
    - docker push registry.gitlab.com/gbraad/ostreetests:fedora
  only:
    - master
  when: manual

build_fedoramine:
  script:
    - docker build -t registry.gitlab.com/gbraad/ostreetests:fedoramine ./mine/fedora
    - docker push registry.gitlab.com/gbraad/ostreetests:fedoramine
  only:
    - master
  when: manual

